import json
import uuid

class NivayaPlanner:
    """
    Execution-Oriented Structured Planning Engine for Nivaya 3.0.
    """
    def __init__(self, tool_registry):
        self.tool_registry = tool_registry

    def decompose_task(self, objective, context=None):
        """
        Breaks objective into atomic steps with NTIS-compliant structure.
        """
        task_id = str(uuid.uuid4())
        available_tools = self.tool_registry.get_available_tools()
        
        print(f"[NivayaPlanner] Decomposing: '{objective}' (Available Tools: {list(available_tools.keys())})")
        
        # Mock logic for atomic decomposition
        # In production, this would be generated by the Nivaya3Model's latent planning head
        plan = [
            {
                "step_id": "step_001",
                "tool": "web_tool",
                "action": "search",
                "parameters": {"query": f"latest data on {objective}"},
                "dependencies": [],
                "priority": "high"
            },
            {
                "step_id": "step_002",
                "tool": "code_tool",
                "action": "execute_python",
                "parameters": {"code": "print('processing data...')"},
                "dependencies": ["step_001"],
                "priority": "medium"
            },
            {
                "step_id": "step_003",
                "tool": "memory_tool",
                "action": "store",
                "parameters": {"key": "task_result", "value": "optimized_data"},
                "dependencies": ["step_002"],
                "priority": "low"
            }
        ]
        
        return {
            "task_id": task_id,
            "plan": plan
        }

    def validate_plan(self, plan_data):
        """
        Ensures the plan only uses available tools.
        """
        for step in plan_data["plan"]:
            if not self.tool_registry.is_tool_available(step["tool"]):
                raise ValueError(f"Plan uses unavailable tool: {step['tool']} in phase {self.tool_registry.phase}")
        return True
